### PR TITLE
Snake_ game  fix ui improvemenrt 

### PR DESCRIPTION
**Pull request by Gokilp**
## Issue ticket number and link 
   issues #72
## Checklist before requesting a review
- [x] Improving UI snake 
- [x]  Changes made in the index.html file and 
- [x]  changes made  src/scripts/themes.js  changed made in color  themes

### CODE REVIEW

**Comment by devsargam** [comment]
Hey @Gokilp, what does this improve? Am I missing something?

**Comment by Gokilp** [comment]
Ui improvement @devsargam 

I made simple changes

Please review my Pr

**Comment by Gokilp** [comment]
Let connect bro

**Review by devsargam — CHANGES_REQUESTED** [review]
Looks like a lot of vague changes

**Comment by devsargam** [comment]
Doesn't look like anything needed. Thanks for the time tho. Closing right now but feel free to open something good.

**Comment by Gokilp** [comment]
@devsargam  Thank you so much Review my PR

**Pull request closed without merging**
